# frozen_string_literal: true

require "rake"
require "rake/testtask"
require "rdoc/task"

APP_RAKEFILE = File.expand_path("config/application", __dir__)
load "rails/tasks/engine.rake"

load "rails/tasks/statistics.rake"

require "rails/dummy_rake_tasks"

task default: :test

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
  t.verbose = false
end
